# Site settings
title: CamWRT
email: vooon341@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  OpenWRT for OEM IP camera modules based on DM368.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  CamWRT

# Build settings
markdown: kramdown
